name: 'nimbusbill'
version: '1.0.0'
config-version: 2

profile: 'nimbusbill'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  nimbusbill:
    staging:
      +materialized: view
      +schema: SILVER
    marts:
      +materialized: table
      +schema: GOLD
