-- dq/checks.sql

-- 1. Idempotency Check (Duplicates in Silver)
SELECT COUNT(*) as DUPLICATE_COUNT
FROM (
    SELECT EVENT_ID, COUNT(*)
    FROM NIMBUSBILL.SILVER.USAGE_EVENTS_CLEAN
    GROUP BY EVENT_ID
    HAVING COUNT(*) > 1
);

-- 2. Negative Quantity Check
SELECT COUNT(*) as NEGATIVE_QTY_COUNT
FROM NIMBUSBILL.SILVER.USAGE_EVENTS_CLEAN
WHERE QUANTITY < 0;

-- 3. Pricing Coverage Check (Unpriced Usage)
SELECT COUNT(*) as UNPRICED_ROWS
FROM NIMBUSBILL.SILVER.USAGE_DAILY_AGG agg
LEFT JOIN NIMBUSBILL.GOLD.DIM_PRICING_RATE p 
    ON agg.PRODUCT_ID = p.PRODUCT_ID 
    AND agg.UNIT = p.UNIT
    AND (agg.EVENT_DATE BETWEEN p.EFFECTIVE_FROM AND COALESCE(p.EFFECTIVE_TO, '9999-12-31'))
WHERE p.RATE_ID IS NULL;

-- 4. Invoice Integrity (Header vs Line Items)
SELECT COUNT(*) as MISMATCH_COUNT
FROM NIMBUSBILL.GOLD.FACT_INVOICES i
JOIN (
    SELECT INVOICE_ID, SUM(AMOUNT) as CALC_TOTAL
    FROM NIMBUSBILL.GOLD.FACT_INVOICE_LINE_ITEMS
    GROUP BY INVOICE_ID
) li ON i.INVOICE_ID = li.INVOICE_ID
WHERE ABS(i.SUBTOTAL - li.CALC_TOTAL) > 0.01; -- Allow small floating point diff
