-- 01_create_bronze_tables.sql
USE SCHEMA NIMBUSBILL.BRONZE;

-- 1.1 Usage Events Raw
CREATE TABLE IF NOT EXISTS USAGE_EVENTS_RAW (
    INGEST_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    SOURCE STRING,
    DT DATE,         -- Partition key
    BATCH_ID STRING, -- Airflow Run ID
    FILE_NAME STRING,
    RAW VARIANT      -- Full JSON Payload
)
CLUSTER BY (DT);

-- 1.2 Customer Accounts Raw
CREATE TABLE IF NOT EXISTS CUSTOMERS_RAW (
    INGEST_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DT DATE,
    BATCH_ID STRING,
    RAW VARIANT
)
CLUSTER BY (DT);

-- 1.3 Pricing Catalog Raw
CREATE TABLE IF NOT EXISTS PRICING_CATALOG_RAW (
    INGEST_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DT DATE,
    BATCH_ID STRING,
    RAW VARIANT
);
