-- 02_create_silver_tables.sql
USE SCHEMA NIMBUSBILL.SILVER;

-- 2.1 Usage Events Clean
CREATE TABLE IF NOT EXISTS USAGE_EVENTS_CLEAN (
    EVENT_ID STRING,
    EVENT_TS TIMESTAMP_NTZ,
    EVENT_DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    PLAN_ID STRING,
    REGION STRING,
    UNIT STRING,
    QUANTITY NUMBER(38,6),
    SOURCE STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING,
    RAW_HASH STRING,
    CONSTRAINT PK_USAGE_EVENTS PRIMARY KEY (EVENT_ID)
)
CLUSTER BY (EVENT_DATE, CUSTOMER_ID);

-- 2.2 Usage Events Quarantine
CREATE TABLE IF NOT EXISTS USAGE_EVENTS_QUARANTINE (
    INGEST_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DT DATE,
    SOURCE STRING,
    ERROR_REASON STRING,
    RAW VARIANT,
    BATCH_ID STRING
);

-- 2.3 Customer Current (Latest Snapshot)
CREATE TABLE IF NOT EXISTS CUSTOMER_CURRENT (
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    STATUS STRING,
    COUNTRY STRING,
    PLAN_ID STRING,
    UPDATED_AT TIMESTAMP_NTZ,
    LOAD_TS TIMESTAMP_NTZ,
    BATCH_ID STRING,
    CONSTRAINT PK_CUSTOMER_CURRENT PRIMARY KEY (CUSTOMER_ID)
);

-- 2.4 Pricing Rates (Effective Dated)
CREATE TABLE IF NOT EXISTS PRICING_RATES (
    RATE_ID STRING,
    PRODUCT_ID STRING,
    PLAN_ID STRING,
    UNIT STRING,
    UNIT_PRICE NUMBER(38,10),
    CURRENCY STRING,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    LOAD_TS TIMESTAMP_NTZ,
    BATCH_ID STRING,
    CONSTRAINT PK_PRICING_RATES PRIMARY KEY (RATE_ID)
);

-- 2.5 Usage Daily Aggregate (Pre-Pricing)
CREATE TABLE IF NOT EXISTS USAGE_DAILY_AGG (
    EVENT_DATE DATE,
    CUSTOMER_ID STRING,
    PRODUCT_ID STRING,
    UNIT STRING,
    TOTAL_QUANTITY NUMBER(38,6),
    EVENT_COUNT NUMBER,
    LAST_EVENT_TS TIMESTAMP_NTZ,
    LOAD_TS TIMESTAMP_NTZ,
    BATCH_ID STRING,
    CONSTRAINT PK_USAGE_DAILY_AGG PRIMARY KEY (EVENT_DATE, CUSTOMER_ID, PRODUCT_ID, UNIT)
);
