-- 03_create_gold_tables.sql
USE SCHEMA NIMBUSBILL.GOLD;

-- 3.1 Dimensions
-- 3.1.1 Date Dimension (Standard)
CREATE TABLE IF NOT EXISTS DIM_DATE (
    DATE_ID DATE PRIMARY KEY,
    YEAR NUMBER,
    MONTH NUMBER,
    DAY NUMBER,
    QUARTER NUMBER,
    DAY_OF_WEEK NUMBER,
    IS_WEEKEND BOOLEAN
);

-- 3.1.2 Customer Dimension (SCD Type 2)
CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_SK NUMBER AUTOINCREMENT START 1 INCREMENT 1,
    CUSTOMER_ID STRING,
    CUSTOMER_NAME STRING,
    STATUS STRING,
    COUNTRY STRING,
    PLAN_ID STRING,
    EFFECTIVE_START TIMESTAMP_NTZ,
    EFFECTIVE_END TIMESTAMP_NTZ,
    IS_CURRENT BOOLEAN,
    RECORD_HASH STRING, -- MD5 of attributes for change detection
    CONSTRAINT PK_DIM_CUSTOMER PRIMARY KEY (CUSTOMER_SK)
);

-- 3.1.3 Product Dimension
CREATE TABLE IF NOT EXISTS DIM_PRODUCT (
    PRODUCT_ID STRING PRIMARY KEY,
    PRODUCT_NAME STRING,
    CATEGORY STRING,
    DESCRIPTION STRING
);

-- 3.1.4 Plan Dimension
CREATE TABLE IF NOT EXISTS DIM_PLAN (
    PLAN_ID STRING PRIMARY KEY,
    PLAN_NAME STRING,
    BASE_FEE NUMBER(38,2),
    CURRENCY STRING
);

-- 3.1.5 Pricing Rate Dimension (SCD2 Style)
CREATE TABLE IF NOT EXISTS DIM_PRICING_RATE (
    RATE_SK NUMBER AUTOINCREMENT,
    RATE_ID STRING,
    PRODUCT_ID STRING,
    PLAN_ID STRING,
    UNIT STRING,
    UNIT_PRICE NUMBER(38,10),
    CURRENCY STRING,
    EFFECTIVE_FROM DATE,
    EFFECTIVE_TO DATE,
    IS_CURRENT BOOLEAN,
    CONSTRAINT PK_DIM_RATE PRIMARY KEY (RATE_SK)
);

-- 3.2 Facts
-- 3.2.1 Daily Usage Fact
CREATE TABLE IF NOT EXISTS FACT_CUSTOMER_DAILY_USAGE (
    DATE_ID DATE,
    CUSTOMER_SK NUMBER,
    PRODUCT_ID STRING,
    UNIT STRING,
    TOTAL_QUANTITY NUMBER(38,6),
    BILLABLE_QUANTITY NUMBER(38,6),
    COST_AMOUNT NUMBER(38,10),
    CURRENCY STRING,
    RATE_SK NUMBER,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING,
    CONSTRAINT FK_FCDU_DATE FOREIGN KEY (DATE_ID) REFERENCES DIM_DATE(DATE_ID),
    CONSTRAINT FK_FCDU_CUST FOREIGN KEY (CUSTOMER_SK) REFERENCES DIM_CUSTOMER(CUSTOMER_SK)
);

-- 3.2.2 Invoices Fact
CREATE TABLE IF NOT EXISTS FACT_INVOICES (
    INVOICE_ID STRING PRIMARY KEY,
    CUSTOMER_SK NUMBER,
    BILLING_PERIOD_START DATE,
    BILLING_PERIOD_END DATE,
    ISSUED_TS TIMESTAMP_NTZ,
    STATUS STRING, -- draft, issued, paid, failed, void
    SUBTOTAL NUMBER(38,10),
    TAX NUMBER(38,10),
    TOTAL NUMBER(38,10),
    CURRENCY STRING,
    LOAD_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    BATCH_ID STRING
);

-- 3.2.3 Invoice Line Items Fact
CREATE TABLE IF NOT EXISTS FACT_INVOICE_LINE_ITEMS (
    INVOICE_ID STRING,
    LINE_ITEM_ID STRING,
    LINE_TYPE STRING, -- base_fee, usage, overage, adjustment, tax
    PRODUCT_ID STRING, -- Nullable for base fees
    UNIT STRING,
    QUANTITY NUMBER(38,6),
    UNIT_PRICE NUMBER(38,10),
    AMOUNT NUMBER(38,10),
    RATE_SK NUMBER,
    USAGE_WINDOW_START DATE,
    USAGE_WINDOW_END DATE,
    CALC_BATCH_ID STRING,
    LOAD_TS TIMESTAMP_NTZ,
    CONSTRAINT PK_FILI PRIMARY KEY (INVOICE_ID, LINE_ITEM_ID)
);

-- 3.2.4 Billing Audit Fact
CREATE TABLE IF NOT EXISTS FACT_BILLING_AUDIT (
    INVOICE_ID STRING,
    LINE_ITEM_ID STRING,
    CUSTOMER_ID STRING, -- Denormalized for easy querying
    PRODUCT_ID STRING,
    EVENT_DATE DATE,
    SOURCE_BATCH_ID STRING, -- Where the usage came from
    AGG_ROW_HASH STRING, -- Link to SILVER.USAGE_DAILY_AGG
    RATE_SK NUMBER,
    CALC_BATCH_ID STRING,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
