-- 04_create_ops_tables.sql
USE SCHEMA NIMBUSBILL.OPS;

-- 4.1 Pipeline Checkpoints (Watermarks)
CREATE TABLE IF NOT EXISTS PIPELINE_CHECKPOINTS (
    PIPELINE_NAME STRING,
    LAST_EVENT_TS TIMESTAMP_NTZ,
    LAST_INGEST_TS TIMESTAMP_NTZ,
    LAST_DT DATE,
    UPDATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_CHECKPOINT PRIMARY KEY (PIPELINE_NAME)
);

-- 4.2 Pipeline Run Audit
CREATE TABLE IF NOT EXISTS PIPELINE_RUN_AUDIT (
    RUN_ID STRING, -- Airflow DagRun ID
    DAG_ID STRING,
    TASK_ID STRING,
    EXECUTION_DATE TIMESTAMP_NTZ,
    STATUS STRING,
    ROWS_INSERTED NUMBER,
    ROWS_UPDATED NUMBER,
    DURATION_SECONDS NUMBER,
    ERROR_MESSAGE STRING,
    CREATED_TS TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);
